FROM nginx:1.21.4

# ADD ../web/nginx.conf /etc/nginx/nginx.conf

# ADD ../web/uwsgi_params /etc/nginx/uwsgi_params

# ADD ../web/default.conf /etc/nginx/sites-enabled/default

# ADD ../web/default.conf /etc/nginx/sites-available/default

RUN mkdir /var/www

RUN mkdir /var/www/front_end

RUN mkdir /var/www/static