# Generated by Django 3.2.9 on 2022-03-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balloon', '0002_alter_postballoon_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postballoon',
            name='title',
        ),
    ]
